/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_maxtable_client_MtAccess */

#ifndef _Included_org_maxtable_client_MtAccess
#define _Included_org_maxtable_client_MtAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    createContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_maxtable_client_MtAccess_createContext
  (JNIEnv *, jclass);

/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    destroyContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_maxtable_client_MtAccess_destroyContext
  (JNIEnv *, jclass);

/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    openConnection
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_maxtable_client_MtAccess_openConnection
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    closeConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_maxtable_client_MtAccess_closeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    openExecute
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_maxtable_client_MtAccess_openExecute
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    closeExecute
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_maxtable_client_MtAccess_closeExecute
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    getNextrow
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jlong JNICALL Java_org_maxtable_client_MtAccess_getNextrow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_maxtable_client_MtAccess
 * Method:    getColValue
 * Signature: (JLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_maxtable_client_MtAccess_getColValue
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
